### ISSUE TITLE
Footer spacing when the Facebook and Twitter icon aren't present

### ISSUE THREAD

**Issue by liyun-li** [eddiesigner/liebling#104]
When the site doesn't have a Facebook link and a Twitter link, there is a wide gap between the copyright information and the string "JavaScript license information," which in my opinion is a little awkward.

Is it possible to have it fixed?

**Comment by eddiesigner** [comment]
Do you mean this gap?

![Screen Shot 2019-12-13 at 13 37 08](https://user-images.githubusercontent.com/1477503/70800936-caf7b300-1dad-11ea-9c1e-1c606c45d8b9.png)

I don't think it looks awkward, I actually like it because both are different things.

But if you still want to change it, you can do it easily by injecting this code into the "Site Header Code injection" section of your Ghost instance:

```html
<style>
.m-footer-copyright,
.m-footer-social {
  margin-bottom: 10px; /* or the space you want */
}
</style>
```

**Comment by liyun-li** [comment]
Thank you! I will go ahead and close this issue.
