### ISSUE TITLE
Add syntax highlights

### ISSUE THREAD

**Issue by mehrdad-shokri** [eddiesigner/liebling#107]
Hi, thanks for the theme. Unfortunately, it doesn't have a very popular feature: Syntax highlighting.  
Other themes usually use [Prism](https://prismjs.com/) for this. What your thoughts on this?

**Comment by eddiesigner** [comment]
I agree it's a popular feature but still there are people that don't need it, I don't want them to load some resources if it's not necessary. I feel more confortable if this feature works as something optional, something that you can include only if you really need it.

Since you will need to make some changes to the template anyways to load the theme you want and to target the languages you want, might be better if I create a page in the Wiki with the instructions to do this and adapt the theme a bit to let people add the Prism scripts easily.

What do you think?

**Comment by mehrdad-shokri** [comment]
Yeah, that would work, but requires users to manually edit the source code.  
Right now users can just grab the zip file and upload it through ghost admin panel but now, they should clone this repo, make changes and publish it again( Besides they need to setup docker, docker-compose to test if it works correctly.)  
I personally edited the source code and set it up manually, but I think users may find it hard to accomplish this task.  
What if we make it config based? The user just set a variable to true, and we do the rest

**Comment by eddiesigner** [comment]
Oh no, you don't have to do all that work to use Prism with this theme. To install Prism you have two main options:

1. Download the zip file, modify the file `default.hbs` to include the stylesheet and the scripts of Prism, zip it and upload it to your Ghost instance.

2. Open the Ghost admin panel, head to the `Code injection` section and then include the stylesheet and the scripts of Prism.

I don't think Prism should be included by default, I think is better if users install it by their own because one way or another, you will end up editing a little the source code to include the theme you want and to include the styles of languages you want. I can't include all the 199 languages and all the 8 themes that Prism support.

**Comment by RealCodeTips** [comment]
Can I offer an alternative option? 

I came across your theme (love it by the way!) and am currently going through the process of adding syntax highlighting to it. I agree that having people put it in the `Code Injection` section is feasible, but it's obviously much better to serve those files locally and not having to use a CDN. 

Perhaps two zip's can be produced, one with prism and the other without?

**Comment by mehrdad-shokri** [comment]
@eddiesigner Since I'm a developer myself, I've already forked this repo, included prism by default in it.  
It gets built with other assets.  
To note my pov, syntax highlighting is something that should be integrated in theme itself (Sorry your soloutions seems hacky to me)  
Like every time you update the theme, the poor client should first download the zip, modify ``defaults.hbs`` and then zip it again?  
Besides, the whole thing talking about is 20KB

**Comment by RealCodeTips** [comment]
@mehrdad-shokri not every person that uses ghost will use code samples, so no it's not an integral part of a theme. 

The author is completely justified in his decision

**Comment by D3473R** [comment]
This should be not included in the theme as default.
The easiest method would be just including the prismjs files via Code Injection as so:
```html
<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-core.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/autoloader/prism-autoloader.min.js"></script>
```

If you want to serve the files yourself you'll have to repack the release zip file with the necessary files.
And if you want to do more custom stuff you can create a fork of this repo and use it as an upstream branch from which you can pull updates.

**Comment by RealCodeTips** [comment]
Like I said before, the most optimal solution would be to create two zips if it's that much of an issue. 

But those who are using code samples are probably skilled enough just to include it themselves.

It should not be added via code injection.

This is such a non-issue and should just be closed.

**Comment by mehrdad-shokri** [comment]
I've forked this repo and added prism as an internal part of the theme.

**Comment by eddiesigner** [comment]
I've created a new page in the Wiki to let users know how to install Prism in order to add syntax highlighting: https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism

The reasons because I think this is the best way to install Prism are the following:

1. Theme agnostic, that means you can keep it even if you change the theme.
2. Most of the time is better to serve this kind of files from a cdn instead of locally.
3. You don't have to touch the source code.
4. You can add the Prism theme you want and you can give support to the languages that you actually need.

I'll close this issue for now, please feel free to reopen it if you think is necessary.
