### ISSUE TITLE
when use Deploy Ghost Theme , Liebling did not work well

### ISSUE THREAD

**Issue by xiyizhou** [eddiesigner/liebling#112]
when use Deploy Ghost Theme , Liebling did not work.
![Snipaste_2020-01-04_16-10-55](https://user-images.githubusercontent.com/55862635/71762718-051c2680-2f0e-11ea-81b7-8cfc918cab37.png)

**Comment by eddiesigner** [comment]
Please take a look to this link https://github.com/eddiesigner/liebling#download

**Comment by ivomota** [comment]
I think this is not invalid. He is talking about that https://github.com/marketplace/actions/deploy-ghost-theme

The problem is, you need to build the theme before creating the zip file and send it.
Or you just need to commit the zip, and deploy it...

But I have the same problem and I din't solve it yet

**Comment by xiyizhou** [comment]
this problem had solved,  see it https://github.com/eddiesigner/liebling/wiki/Github-Action-Deployment

**Comment by ivomota** [comment]
Thank you @xiyizhou! My mistake. 
It works now for me to 👍
