### ISSUE TITLE
unknown words are showing on Post detail page for multiple authors name

### ISSUE THREAD

**Issue by keyuls** [eddiesigner/liebling#118]
It is showing 'no break line' on the post detail page when post has multiple authors.

![image](https://user-images.githubusercontent.com/8844721/71787830-7ecd1680-2fd9-11ea-8507-5cf6a5bc2a0a.png)

**Comment by D3473R** [comment]
Have you modified your locale json file?
There should be a line: `"Among with no break line": "Among with ",` which resolves the displayed string. In the default english locale for example:
<img width="410" alt="2020-01-06 11_55_31-Welcome to Ghost" src="https://user-images.githubusercontent.com/10356892/71814074-ad033280-307b-11ea-9e11-8cab20de3eca.png">

**Comment by eddiesigner** [comment]
Yeah, it looks like you modified a locale json file or the `post.hbs` file, maybe you removed a double quote or something like that by mistake. Please check your files or please download the theme again.

**Comment by keyuls** [comment]
I downloaded zip file from https://github.com/eddiesigner/liebling/releases page and uploaded zip directly to ghost blog. No additional change made to zip file.

Ghost Version 2.27.0

**Comment by eddiesigner** [comment]
What language locale are you using?

This is so weird, the line involved here is:

```hbs
{{authors separator=", " prefix=(t "Among with no break line") from="2"}}
```

`prefix=(t "Among with no break line")` is a subexpression which is supported since Ghost v0.4: https://ghost.org/docs/api/v3/handlebars-themes/helpers/translate/#subexpressions

As an alternative you can edit the file `post.hbs` and edit the line [#108](https://github.com/eddiesigner/liebling/blob/master/post.hbs#L108) like this:

```hbs
{{authors separator=", " prefix="Among with " from="2"}}
```

The `prefix` value can be anything you want.

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if you think is necessary.
