### ISSUE TITLE
Slow Helper warning 

### ISSUE THREAD

**Issue by keyuls** [eddiesigner/liebling#121]
Is it possible to improve the helper timing? someone suggested on [ghost blog](https://forum.ghost.org/t/warn-cookie-members-ssr-not-found-each-get-command/8669/2) to improve helper timing for overall performance.

![image](https://user-images.githubusercontent.com/8844721/71953167-8ee22300-319e-11ea-894a-876cb54f8f92.png)

**Comment by eddiesigner** [comment]
I'm not sure about this, I'm doing that following the recommendation from the docs:

> The most effective way to show posts that are related by topic in your related posts block is to filter by tag. For example:
https://ghost.org/tutorials/related-posts-block/

```hbs
{{#get "posts" limit="5" filter="tags:[{{post.tags}}]+id:-{{post.id}}" include="tags" as |related|}}
{{/get}}
```

The only difference is that I include the `authors` since I need this data to display the author info.

I would say the number of tags also has to do something with that timing, probably with less tags would be a bit faster. Also maybe there are another factors like the database and server environments 🤔 .

You can try to edit the file `post.hbs` and replace the line above with this one:

```hbs
{{#get "posts" limit="5" filter="tags:[{{post.primary_tag}}]+id:-{{post.id}}" include="tags" as |related|}}
```

I'm not sure if it actually works or not but the idea is to filter just by the primary tag instead of filter by all the tags.
