### ISSUE TITLE
Hide or Remove Header

### ISSUE THREAD

**Issue by adusingi** [eddiesigner/liebling#130]
I would love to remove the header sections.
Can you please point me to the help on this? Thank you
Want to remove all this
> header class="m-hero with-picture aos-init aos-animate" data-aos="fade" 
>  /header

Currently I have my header like this (https://blog.dokomaps.com/)

![image](https://i.snap.as/7mgj7wP.png)

I would like to remove the header and have my blog start at div "m-article-card post" section

![image](https://i.snap.as/JPg6Xw1.png)

Thank you

**Comment by eddiesigner** [comment]
Do you want to remove it from all the pages or just from the home page?

I'm asking that because that element is an important part of some pages like the post, page, authors, author and tag pages, it's not a good idea to remove it from there.

If you only want to remove it from the home page just remove the following code from the `index.hbs` file:

```hbs
  {{!-- Inject styles of the hero image to make it responsive --}}
  {{> hero background=@site.cover_image}}
  <div class="m-hero__content" data-aos="fade-down">
    <h1 class="m-hero-title bigger">{{@site.title}}</h1>
    {{#if @site.description}}
    <p class="m-hero-description bigger">{{@site.description}}</p>
    {{/if}}
    {{#if @labs.subscribers}}
    <a href="{{@site.url}}/subscribe" class="m-button filled">{{t "Subscribe"}}</a>
    {{/if}}
  </div>
  </section>
```

Then inject these styles in the Code injection page (Blog Header section) of your Ghost admin panel:

```html
<style>
.l-content {
  padding: 70px 0 20px;
}

.m-featured-slider {
  margin: -20px -20px 40px;
}

@media only screen and (min-width:64rem) {
  .l-content {
    padding: 100px 0 40px;
  }

  .m-featured-slider {
    margin:0 20px 40px;
  }
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
