### ISSUE TITLE
SECONDARY NAVIGATION in the footer

### ISSUE THREAD

**Issue by xiyizhou** [eddiesigner/liebling#131]
I want to add authors/about pages as SECONDARY NAVIGATION in the footer, can you please suggest me how can i do this?

**Comment by eddiesigner** [comment]
Do you mean this? https://ghost.org/changelog/secondary-navigation/

At the moment this theme doesn't support that feature since that is only available in Ghost 3, I have plans to give full support to that version in the near future though.

**Comment by xiyizhou** [comment]
yes,  you are right. I look forward to seeing SECONDARY NAVIGATION in this theme.

**Comment by polyinnovator** [comment]
I find that this hasn't been resolved. Sure the secondary navigation is added, but it is only a dropdown in the header menu.

What Xi was saying was something for the footer, as well as Bern was saying more social media icons. Both of which would be appreciated.

**Comment by eddiesigner** [comment]
@xiyizhou  This is finally implemented in [version 0.8.8](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.8) ;)

@polyinnovator You can see in [this comment](https://github.com/eddiesigner/liebling/pull/149#issuecomment-619358997) that I already added more icons. I can't add more and more icons because I don't know what icons people might need and because if I add more, the font size will increase more and more.

**Comment by xiyizhou** [comment]
thanks for your hard work @eddiesigner
