### ISSUE TITLE
Adding more social share button

### ISSUE THREAD

**Issue by Vibhigupta** [eddiesigner/liebling#147]
I really loved this theme but I really want more share buttons not just Facebook and Twitter. e.g. What'sapp, reddit and email would be more than enough 

Adding third party code increases the page size and page speed take a hit as well privacy.

If you don't want to add those buttons can you please help me by giving me pieces of code. 

Thank you

**Comment by eddiesigner** [comment]
I would prefer no adding more share buttons since not all the people might need them and because that would make the theme a bit less clean.

The most recent version of this theme includes more social icons: https://github.com/eddiesigner/liebling/blob/713caf7336103c557bc0410f4a02143e2552928f/src/sass/common/_icons.scss

If you really want more share buttons you can modify a bit the `post.hbs` template, specifically what is inside of the `.m-share` element (https://github.com/eddiesigner/liebling/blob/master/post.hbs#L37).

The idea is that you can use the facebook or twitter buttons as reference, copy the code and just replacing the icon and the url. After that you might want to modify the styles as well to reduce the margin between buttons to make more room for more buttons:

```html
<style>
  .m-icon-button.in-share {
    margin: 0 5px;
  }

  @media only screen and (min-width:64rem) {
    .m-icon-button.in-share {
      margin:0 0 5px;
    }
  }
</style>
```

You can inject those styles into the _Code Injection_ page of your Ghost admin (Site Header section)

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
