### ISSUE TITLE
Third party requests

### ISSUE THREAD

**Issue by kayg04** [eddiesigner/liebling#153]
Currently, the theme loads 4 external scripts.

![liebling](https://user-images.githubusercontent.com/30401343/77906548-a8fc4080-7277-11ea-8320-485772ab63d0.png)

If I am already using a CDN to serve a ghost webpage, these third party requests seem unnecessary. Would it be possible to add an option / inject code to serve these resources directly?

**Comment by eddiesigner** [comment]
The first two requests are related to the Google Fonts, i find the current way to load them better because not all the people use a CDN, they might have a regular server with any cache method configurated. I thinkg Google makes a very good job serving fonts, the response is fast, you don't have to configurate anything and the best part is that the fonts are loaded asynchronously.

If you want to host them locally you can use [google webfonts helper](https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=latin) and then download the fonts, put them in some folder within `/assets/fonts/`.

Then you will need to modify the `default.hbs` template to remove the current script that loads the Google fonts: https://github.com/eddiesigner/liebling/blob/master/default.hbs#L44

Finally you will need to create some font-faces (one per each font weight variation) and include them into the `default.hbs` template, just like I did with the icon font: https://github.com/eddiesigner/liebling/blob/master/default.hbs#L15

---------------------

The request to polyfill.io is necessary in order to load only the polyfills that are needed by the requesting browser, previously I was doing it manually but the problem was that the bundle size was bigger because even if the polyfill wasn't in use, the whole file was downloaded. In this way if polyfills are not required then nothing is downloaded.

If you want to host the polyfills on your server, you will need to create a file that includes all the polyfills used on this theme:

* IntersectionObserver
* Promise
* Array.prototype.include
* String.prototype.endsWith
* String.prototype.startsWith
* Object.assign
* NodeList.prototype.forEach

Then you will need to load that file within the `default.hbs` file and remove the script that uses polyfill.io: https://github.com/eddiesigner/liebling/blob/master/default.hbs#L74

Of course if you don't really care about older browsers you can just remove that script.

---------------------

The last request loads the Ghost Content API module, in a future release I will include that module without making a request, in the meantime you can create a file within `/assets/js` and paste the content of `https://unpkg.com/@tryghost/content-api@1.2.7/umd/content-api.min.js`

Then you will need to replace the script source that loads this module in the `default.hbs` file: https://github.com/eddiesigner/liebling/blob/master/default.hbs#L75

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
