### ISSUE TITLE
Problem with Gscan (Installation of theme)

### ISSUE THREAD

**Issue by epegase** [eddiesigner/liebling#161]
Dear,

I want to install the latest version of theme but i throw an error... i think it is related to gscan and some css files... See the images below : 

![image](https://user-images.githubusercontent.com/19345165/79073275-86d5da00-7cdd-11ea-87e1-15a5386aa8ec.png)

**Comment by eddiesigner** [comment]
Please make sure to download the latest version of the theme from the [releases page](https://github.com/eddiesigner/liebling/releases).

You have to download the file `liebling.zip`

**Comment by ErisDS** [comment]
Hey @eddiesigner would you possibly consider committing the built files so that the standard GitHub download is the correct file?

Your theme is _super_ popular, which is fantastic, but means we get a lot of support requests from people making this same mistake. 

Would sure be appreciated ❤️ 

It would also be a temporary stop-gap as we're thinking heavily atm about how to make it much easier to install themes 🙂

**Comment by eddiesigner** [comment]
@ErisDS I already added the built files to the repository 👍 I hope this can improve the overall experience for the users.

I look foward to some new way to install and update themes 🙂. Maybe you guys can implement some sort of marketplace for free themes right into the Ghost admin panel so people can install and update them easily 🤔 . I think you guys can integrate themes repositories and Ghost in a really cool way.
