### ISSUE TITLE
Images are not load in search results

### ISSUE THREAD

**Issue by thimiraonline** [eddiesigner/liebling#167]
How to get the images for search results. I mean the image that relevant image for tye each search result. I have activated the search. But it doesn't load images. I saw on another site they have images in search results.

Result without images (my site)
![image](https://user-images.githubusercontent.com/62184599/79680389-ae242e00-822c-11ea-9956-f2fdc0ac9ea9.png)

Results with images (on another site)
![image](https://user-images.githubusercontent.com/62184599/79680424-170ba600-822d-11ea-803c-e6f45d110a6f.png)

How to add images?

**Comment by eddiesigner** [comment]
The original design of this theme doesn't show images on search results, if you want to do it, you'll need to modify the main script and add your own markup and styles.

I see that you've modified the look of the theme a bit, so you may already be familiar with this guide: https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker. That guide is important because you'll need to modify the file `src/app.js` and compile it to generate a custom version of this theme.

As I said before, open the file `src/app.js` and add this code after line 44:

```js
let observer = null
```

Then remove `const` from line 289:

```js
observer = lozad('.lozad', {
```

Then add `feature_image` to line 93:

```js
fields: 'id, title, url, published_at, custom_excerpt, html, feature_image'
```

Then add this code after line 192:

```js
const resultImage = results[i].feature_image ?
          `<a href="${results[i].url}" class="m-result__image">\
              <div class="lozad" data-background-image="${results[i].feature_image}"></div>\
            </a>` : ''
```

You can use a different markup if you want, this is just a proposal, the important thing is that you use the class `lozad` and the data attribute `data-background-image`.

Then you have to include the variable `resultImage` in the `htmlString` string, maybe like this:

```js
htmlString += `
          <article class="m-result">\
            <a href="${results[i].url}" class="m-result__link">\
              ${resultImage}\
              <h3 class="m-result__title">${results[i].title}</h3>\
            ...
```

Please note that you'll need to provide your own styles for the markup and maybe modify a bit the current styles of the results elements so they look as you want.

Finally after the current line 204 add this code:

```js
observer.observe()
```

**Comment by thimiraonline** [comment]
There are only  186 lines. I'm not familiar with the core files. I'm working with the theme files. 

![image](https://user-images.githubusercontent.com/62184599/79700082-f71dc600-82b0-11ea-90c9-0afc92bf18b0.png)

**Comment by eddiesigner** [comment]
I guess you have an old version. Please pull the latest changes from this repository or clone it again.

This is the current version of that file: https://github.com/eddiesigner/liebling/blob/master/src/js/app.js

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
