### ISSUE TITLE
How to Deploy this theme

### ISSUE THREAD

**Issue by chaitanyasaxena97** [eddiesigner/liebling#171]
Hello Will you please tell me how you deploy this theme? which platform you use for deployment?

**Comment by eddiesigner** [comment]
Hi,

I don't use any particular platform to deploy my Ghost instance, I have my own server and I followed these steps to install it there: https://ghost.org/docs/install/ubuntu/

The way to install themes in Ghost is the same for all of them.

Btw, your question is a bit off-topic since Ghost deployment is not related to this theme, I suggest you to head to the [forum](https://forum.ghost.org/) where you can get help from multiple people about Ghost in general 😉

**Comment by chaitanyasaxena97** [comment]
Thanks for the reply yeah I will take care of this in future 😊
