### ISSUE TITLE
Slideshow in the publication cover section?

### ISSUE THREAD

**Issue by asitkhanda** [eddiesigner/liebling#18]
Instead of just having a single cover image for the publication cover, is it possible to have a series of images running as a slider in the background?! 
I am building a personal photography website and it would be a really cool feature to have that!

**Comment by eddiesigner** [comment]
The problem with that is Ghost doesn't provide a place where you can upload (and manage) those images, you'll need to upload them somewhere else and then paste the links into the code editing the template everytime you need to change/add them.

It's possible to put a slider but the main issue is what I said before, I can't do it this way because is a very specific and non intuitive way to do it.
