### ISSUE TITLE
Question about Liebling theme

### ISSUE THREAD

**Issue by JustHmmmm** [eddiesigner/liebling#186]
Hmmm, I haved replace default icon pack with Unicons icons. Can I upload it to Github? I named it "unibling", can you link my repo forr custom version of liebling? Thank you very much. Sorry about my bad English.

**Comment by eddiesigner** [comment]
Sure you can publish it on GitHub, just be aware that you'll be responsible for maintaining it. If someone creates an issue in your repository, please don't create it in mine as well, you will have to offer support on your own.

I can't link it at the moment because I can't see it working. I can do it as soon as the demo link works.
