### ISSUE TITLE
Adding a custom preloader ⌛

### ISSUE THREAD

**Issue by liebling-love** [eddiesigner/liebling#187]
Hey! 👋😃 I am a very beginner level front end dev, I love to learn new things. I am designing a small personal blog for me and I am using your theme it is very awesome theme 😍. I was thinking about if there is any way that we can enable or add a custom **"preloader"** ([sample 1](https://codepen.io/majci23/pen/NqdXvy), [sample 2](https://codepen.io/Ruddy/pen/RNRybN)) for the website so it will show up on screen instead of blank screen until everything loaded because I saw this blank screen showed up until everything loaded. Sorry if I sounds like noob because I am trying to learn new things. I hope you can navigate me.
Thank you! ❤️

**Comment by eddiesigner** [comment]
Hey 👋🏼

Adding a preloaded is not an easy thing to do since it requires quite work in order to know exactly when all the data and all the resources are downloaded and ready to use, it's not just about displaying a fancy css animation.

Also I believe that a preloader is bad for UX in this case and you have to ask yourself if it's something that you really need, I would say no. I say it's bad for UX because the user can't use the website until you decide to hide the preloader, maybe for complex apps is useful but not for a blog where I think is more important to let users to read the content as soon as possible even if some resources are not ready yet.

I guess you can implement it as a fake preloader. For example, to implement a fake loader that looks like the first example, you can do the following:

1. Copy the HTML from that example and paste it after the `<body>` tag in the file `default.hbs`

2. Then you can use the style from that example and inject it into the _Header_ section of the _Code injection_ page in your admin panel. You can't use SCSS so you have to convert it to CSS first.

3. Finally paste the following code into the _Footer_ section of the _Code injection_ page in your admin panel:

```html
<script>
window.addEventListener('load', function() {
  const preloader = document.querySelector('.loader');
  preloader.remove();
});
</script>
```

**Comment by liebling-love** [comment]
Thanks a lot ❤️  it worked 💯 👍
