### ISSUE TITLE
m-article-card__title post title excerpt?

### ISSUE THREAD

**Issue by GlenSmale** [eddiesigner/liebling#197]
I recently started using the liebling theme for a project, really great work thank you.

I have a question though about the length of the m-article-card__title post title excerpt. I note that some of my longer post titles are shortened with ... I would like to ask if the m-article-card__title post title has an excerpt applied and if it may be possible to increase the length as I would like to show the whole title of my blog posts? I also noted that app.js had custom_excerpt in the script.

Thanks in advance Glen

**Comment by eddiesigner** [comment]
Yep, there is a script that is responsible of shorten the titles if they are pretty long, that's because on desktop the article cards have a fixed height so they look aligned. The titles in article cards are shortened when their height exceeds **100 pixels** or when the article cards don't have an image and the title height exceeds **250 pixels**.

If you want to increase the allowed height number you can do it by modifying the lines [321](https://github.com/eddiesigner/liebling/blob/8564e643111314ed8ecb191006bc573912b3f919/src/js/app.js#L321) and [322](https://github.com/eddiesigner/liebling/blob/8564e643111314ed8ecb191006bc573912b3f919/src/js/app.js#L322) in the file `src/app.js`

You could also remove them to avoid this behavior. If you do this please don't forget to remove this line as well:

```js
import shave from 'shave'
```

You might wanna take a look on the docs to know how to work with this theme in develeopment mode so you can make those changes and make a new build: https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker

Additionally, you would need to increase the height of the article cards. You can do this by heading to _Admin panel -> Code injection_ and injecting the following code into the _Site Header_ section:

```html
<style>
.m-article-card {
  @media only screen and (min-width:48rem) {
    height: 420px; /* Increase the height as you want */
  }
}
</style>
```

**Comment by GlenSmale** [comment]
Thanks Eddie, everything worked well, I just needed to adjusted the size in app.js and not for .m-article-card.
