### ISSUE TITLE
Share bar on mobile

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#209]
Hello,

the post bar on mobile isn't very clear. it would be better to have the same on desktop and mobile.
i want to add affiliate links to songs and artists. it doesn't look good with 5 links.

https://soundsirius.digitalpress.blog/golden-rule-trust/?internal

i think i want to remove facebook and twitter share buttons and only keep affiliate links.

**Comment by eddiesigner** [comment]
Why it's not that clear? The buttons are the same, although the design can't be the same because on mobile they will hide a lot of content, specially if you want 5 buttons there. You can change it if you want but you have to do it by your own, that's something that I won't change since that's very specific for your use case.

I would suggest to keep the same design and only reduce the margin of those buttons on mobile if you want to have 5 buttons.

You can add your own buttons inside of the [share element](https://github.com/eddiesigner/liebling/blob/master/post.hbs#L38), just use the same structure from the existing buttons.

Then you can paste these styles in your Ghost Admin:

```html
<style>
.m-icon-button.in-share {
  margin: 0 15px; /* You can use a different value if you want */
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this issue for now, please fell free to reopen it if needed.
