### ISSUE TITLE
CSS loaded twice (Casper alright)

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#210]
Hello
I wanted to let you know the yellowlab.tools audit site reports the css in liebling is loaded twice.
This might contribute to the reduced speed. But I also want to let you know Casper and Tailwind don't work normally when I copy/paste elements found on other websites (which is the case with Liebling, thank god).

<img width="1440" alt="liebling" src="https://user-images.githubusercontent.com/1311831/85320290-8ae75a80-b4cb-11ea-9b2d-3f2d9a7b9aaf.png">
<img width="1440" alt="casper" src="https://user-images.githubusercontent.com/1311831/85320298-8e7ae180-b4cb-11ea-9463-6742885b2d74.png">
<img width="1440" alt="casper" src="https://user-images.githubusercontent.com/1311831/85320305-90dd3b80-b4cb-11ea-8b73-e96375ec325b.png">

**Comment by eddiesigner** [comment]
Liebling doesn't load the stylesheet twice ([as you can see here](https://github.com/eddiesigner/liebling/blob/master/default.hbs#L28)), it seems like you've done changes by your own since this theme doesn't include Tailwindcss and also doesn't include a file called `screen.css`. Please check your changes and fix it there. I'm closing this issue since there is nothing to solve on my side.
