### ISSUE TITLE
Specify another font than Source Sans Pro

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#211]
Hello,
I want to select a specific font called Fredoka One. I managed to do it easily but now I have to remove all references to Source Sans Pro. How can I do that? I can't edit the theme right now because of my host. I wanted to do it in JS. If you want to have a look at your theme with another font, head here :) 
https://soundsirius.digitalpress.blog/

**Comment by eddiesigner** [comment]
Hi,

I can see the same font (Source Sans Pro) on your blog, if you want to know how to use a custom font please take a look to [this issue](https://github.com/eddiesigner/liebling/issues/84).

I'm closing this issue because this topic is already solved and because if you want to make changes, is better if you do it locally and then upload your customized version through the Ghost admin interface, it's not a good idea to make changes directly on your server because they will be gone whenever you upload the theme again or for any other reason.

Also you can't do it with javascript.
