### ISSUE TITLE
Add Table of Contents for Posts

### ISSUE THREAD

**Issue by kmanojkumar** [eddiesigner/liebling#216]
Hi,

Loved the minimalist design of the theme, and performance.

Can you please guide on how to add Table of Contents to the posts, sticky on the left side? It's very helpful for readers to navigate the article quickly and improve the overall experience. I attached a quick design reference. 

![Screenshot 2020-07-01 at 1 03 35 PM](https://user-images.githubusercontent.com/14366356/86216359-8988f280-bb9b-11ea-96a8-28f10244c2d0.png)

I tried using https://ghost.org/tutorials/adding-a-table-of-contents/, but it looks really odd, and not in sync with the theme design.

Thanks in advance!

**Comment by eddiesigner** [comment]
Hi,

The goal of this theme is to be as clean and simple as possible, I'm afraid that a Table of Content is something that not all of the blogs need, that's why I didn't include it as part of this theme.

I think that tutorial is a pretty decent guide to achieve it, also you can see [this other issue](https://github.com/eddiesigner/liebling/issues/146), maybe it helps you in some way.

You can try to use some colors that this theme uses to keep it in sync with the design.

Cheers.

**Comment by eddiesigner** [comment]
I'll close this issue for now, please feel free to reopen it if needed.
