### ISSUE TITLE
Show all post tags

### ISSUE THREAD

**Issue by curiousdungbeetle** [eddiesigner/liebling#217]
Hello! I love this theme, thank you so much for creating it.
One small issue: if I create a post with multiple tags, only the main tag is shown on the post itself. Is there a way to show all tags, maybe at the bottom? 
I'm (very) slowly learning handlebars...
Thank you!

**Comment by eddiesigner** [comment]
Hi!

You can paste this code after [line 59](https://github.com/eddiesigner/liebling/blob/master/post.hbs#L59) in the `post.hbs` file:

```hbs
{{!-- List of tags  --}}
{{#if tags}}
  <section class="m-tags in-post">
    <h3 class="m-submenu-title">{{t "Tags"}}</h3>
    <ul>
      {{#foreach tags}}
        <li>
          <a href="{{url}}" title="{{name}}">{{name}}</a>
        </li>
      {{/foreach}}
    </ul>
  </section>
{{/if}}
```

Then you can inject these styles in your Ghost admin:

```html
<style>
.m-tags.in-post ul {
  padding: 0;
  list-style-type: none;
}

.m-tags.in-post a {
  text-decoration: none;
}
</style>
```

**Comment by curiousdungbeetle** [comment]
Thanks a bunch, worked perfectly. And it helps me learn about changing the theme myself, so I should be able to bother you less! All the best.

**Comment by tribet84** [comment]
Any chance to get this feature in the normal release?

**Comment by eddiesigner** [comment]
@tribet84 It's already implemented in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.1) ;)

**Comment by tribet84** [comment]
Outstanding response time! 
I see the new tags section at the end of the post but the theme still shows only one tag under the title within the post and in home, [example](https://blog.orvium.io/orvium-platform-release-1-10/)

Would it be possible to show all tags anywhere a tag is displayed?

Ps. I moved from v0.7.3 to this v0.8.1 and comments stop working.

**Comment by eddiesigner** [comment]
The idea is to show only the [primary tag](https://ghost.org/docs/api/v3/handlebars-themes/context/post/#primary-tag) in article cards or under the title in post pages, not to show the whole list of tags everywhere, that would make the theme unnecessarily complex and bloated.

If you followed [this guide](https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog) to enable comments in your blog, you have to do it again since the templates are overwritten when you update the theme. I understand that is not optimal but currently there is no another way to do it (this applies to any other Ghost theme).
