### ISSUE TITLE
Support Responsive images

### ISSUE THREAD

**Issue by kmanojkumar** [eddiesigner/liebling#226]
The theme drastically improved its performance so far. 

I was wondering if you could support responsive images to save a ton of page size.

I found [this](https://ghost.org/docs/api/v3/handlebars-themes/responsive-images/) article, but I am not sure if liebling theme supports responsive images as such? Or what it takes to configure maybe.

Any plan to include in a future release? Because, I am sure that would push the bars really high in terms of pagespeed. 

Thanks!

**Comment by eddiesigner** [comment]
This theme actually implements responsive images AND lazy loading which means, only images that are visible within the viewport are in fact downloaded.

For hero images I use different breakpoints to decide what image to download based on screen size as you can see here: https://github.com/eddiesigner/liebling/blob/master/partials/hero.hbs

For featured articles I follow the same approach as you can see here: https://github.com/eddiesigner/liebling/blob/master/index.hbs#L55

For article cards only one size is needed since the width doesn't vary too much, is pretty much the same width on mobile and desktop, as you can see below I load a medium size image (to support retina screens as well) and they are loaded with lazy loading:

```hbs
<img class="m-article-card__picture-background" src="{{img_url feature_image size="m"}}" loading="lazy" alt="">
```

Finally I recommend you to not use Unsplash directly in the Ghost admin when editing a post because Ghost doesn't generate small versions for those images, it only does it when you upload images through the input file.

**Comment by kmanojkumar** [comment]
Perfect. Thanks for the information!
