### ISSUE TITLE
amount of search results displayed

### ISSUE THREAD

**Issue by vvcodes** [eddiesigner/liebling#230]
Hello, is it possible to limit the number of results displayed on result page ? since alot of posts contain same term in my blog and it got hundreds of posts.

**Comment by ayyilmaz** [comment]
Currently, search feature is not working. You can test: https://istihbarat.club

**Comment by ayyilmaz** [comment]
> Hello, is it possible to limit the number of results displayed on result page ? since alot of posts contain same term in my blog and it got hundreds of posts.

Currently, search feature is not working. You can test: https://istihbarat.club

**Comment by eddiesigner** [comment]
Hi, i just released a new version which improves the search, I encourage you to download it first and try it, this new version only searches in the titles and in the excerpts of the posts, previously it also searched in the content of the posts so now there should be less and better results. You can download the latest version in the [releases page](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.1).

After that, if you still want to limit the number of results, you have to change a bit the file [`app.js`](https://github.com/eddiesigner/liebling/blob/master/src/js/app.js). In order to do that you have to follow first [this guide](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) to create a custom version of this theme.

Then you have to look for this piece of code:

```js
for (let i = 0, len = bestResults.length; i < len; i++) {
  htmlString += `
  <article class="m-result">\
    <a href="${bestResults[i].item.url}" class="m-result__link">\
      <h3 class="m-result__title">${bestResults[i].item.title}</h3>\
      <span class="m-result__date">${formatDate(bestResults[i].item.published_at)}</span>\
    </a>\
  </article>`
}
```

and change it like this:

```js
for (let i = 0, len = bestResults.length; i < len; i++) {
  if (i >= 10) { // limit of ten results
    break
  }

  htmlString += `
  <article class="m-result">\
    <a href="${bestResults[i].item.url}" class="m-result__link">\
      <h3 class="m-result__title">${bestResults[i].item.title}</h3>\
      <span class="m-result__date">${formatDate(bestResults[i].item.published_at)}</span>\
    </a>\
  </article>`
}
```

You can't change it directly in the javascript file that is located in the `assets` directory because that file is minified for performance reasons and it's overwritten in every new release.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.

**Comment by vvcodes** [comment]
Ok thanks for the information.. so i looked up the file app.js but couldnt found the piece of code you mentioned.. however following is the most similar piece of code i could find in it.

{
                    if (k.val().length > 0 && S) {
                        var e = S.search(k.val()),
                            t = "";
                        if (e.length > 0) {
                            for (var n = 0, a = e.length; n < a; n++) t += '\n          <article class="m-result">
.... blah blah blah .. 
  </article>`
}

please help me with this one.
