### ISSUE TITLE
The layout of the browser is messed up when zooming in

### ISSUE THREAD

**Issue by happyhuizai** [eddiesigner/liebling#246]
The layout of the browser is messed up when zooming in

Safari Browser
version 13.1 (15609.1.20.111.8)

![Kapture 2020-07-30 at 10 45 47](https://user-images.githubusercontent.com/29218617/88875389-c2c48900-d253-11ea-9552-d69b4464c2e6.gif)

**Comment by eddiesigner** [comment]
This only happens in Safari, probably only in the latest version. I don't think there is an issue with the theme itself but with Safari, if you enable the developer menu and then inspect the styles, as soon as you change any style the layout is rendered correctly, actually there are [more people having this exact issue](https://stackoverflow.com/questions/63136590/safari-13-doesnt-apply-css-after-resize).

Maybe Safari has a problem with some style rule or something like that but it would be really hard to know what could be, that's why I will wait to see if this is fixed in a next update.

**Comment by happyhuizai** [comment]
After I deleted this (_submenu.scss) file, it was normal.
But I'm still looking for specific reasons

**Comment by happyhuizai** [comment]
I deleted this (_submenu.scss) file and it worked fine.
But I'm still trying to find out why.

**Comment by eddiesigner** [comment]
This is not happening anymore on Safari 14 😅

**Comment by eddiesigner** [comment]
I'm doing some cleaning up so I'll close this issue for now, please feel free to reopen it if needed.
