### ISSUE TITLE
Feature Request: Add links to Twitter, RSS Feed, Search on the top right corner

### ISSUE THREAD

**Issue by MereCivilian** [eddiesigner/liebling#249]
Hello

See attached image. This will be a handy edition for any visitor to your website. Showing several ways, you can engage with the website. 

It will go well right next to the toggle for the dark mode.

Also can be added to the bottom of the page, next to the twitter account.

<img width="184" alt="Screen Shot 2020-08-01 at 12 02 10 pm" src="https://user-images.githubusercontent.com/68980168/89091719-f7207c80-d3ee-11ea-9093-515641ffd8f1.png">

**Comment by eddiesigner** [comment]
Hi,

Personally I'm not a super fan of having social links in that section, people probably will start adding more and more icons and that's not the idea, I want to keep the header simple and leave more space for the main menu.

What I like is the RSS idea, that's why in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) I added it in the footer.

If you really want to have those links in the top bar I would suggest to download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) and then paste the following code after [line 116](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L116) in `partials/header.hbs`:

```hbs
{{#if @site.facebook}}
  <a href="{{facebook_url @site.facebook}}" class="m-icon-button in-menu-main" target="_blank" rel="noopener" aria-label="Facebook">
    <span class="icon-facebook" aria-hidden="true"></span>
  </a>
{{/if}}
{{#if @site.twitter}}
  <a href="{{twitter_url @site.twitter}}" class="m-icon-button in-menu-main" target="_blank" rel="noopener" aria-label="Twitter">
    <span class="icon-twitter" aria-hidden="true"></span>
  </a>
{{/if}}
<a href="{{@site.url}}/rss" class="m-icon-button in-menu-main" aria-label="RSS">
  <span class="icon-rss" aria-hidden="true"></span>
</a>
```
