### ISSUE TITLE
Modifying the search bar for better results ! 

### ISSUE THREAD

**Issue by gautam-bits** [eddiesigner/liebling#252]
Hi everyone, can we also modify the search bar to also search for author's name and tag's name along with the title and custom excerpt, I have changed the `getAllPosts(host, key)`  function a bit:- 
https://github.com/gautam-bits/liebling/blob/28100d2bdee73d48b838df4b552b3e89a80e13e1/src/js/app.js#L74-105
```javascript
  function getAllPosts(host, key) {
    const api = new GhostContentAPI({
      url: host,
      key,
      version: 'v3'
    })
    const allPosts = []
    const fuseOptions = {
      shouldSort: true,
      ignoreLocation: true,
      findAllMatches: true,
      includeScore: true,
      minMatchCharLength: 2,
      keys: ['title', 'custom_excerpt', 'authors.name', 'tags.name']
    }


    api.posts.browse({
      limit: 'all',
      include: 'authors,tags',
      fields: 'id, title, url, published_at, custom_excerpt'
    })
      .then((posts) => {
        for (let i = 0, len = posts.length; i < len; i++) {
          allPosts.push(posts[i])
        }


        fuse = new Fuse(allPosts, fuseOptions)
      })
      .catch((err) => {
        console.log(err)
      })
  }
```

**Comment by aakashhemadri** [comment]
Yeah I'd like this feature

**Comment by gautam-bits** [comment]
@aakashhemadri  yes, it works with both type of tags

**Comment by eddiesigner** [comment]
I agree that searching across tags might be useful, that's why I already implemented it in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5). However, I don't think searching across authors is a good idea, I don't see people searching for author names, maybe for you could be useful for some reason but that's something that I won't implement. Anyway, thanks for the proposal!
