### ISSUE TITLE
Disqus is not visible

### ISSUE THREAD

**Issue by BurgerhoutJ** [eddiesigner/liebling#254]
I followed the guide to integrate my Disqus account with my blog, but the Disqus is not visible. I'm running Ghost in Docker, so I hope that this is not the case.

**Comment by eddiesigner** [comment]
This is the first time someone has this problem, that's why I think you made a mistake in some point. Please follow the guide carefully and make sure that the code is not commented, please also check that your Disqus configuration is correct and that you're using the correct `shortname`.

You can see the comments working in the demo website: https://liebling.eduardogomez.io/pos-hardware-more-options-in-less-space/

You can also try to restart your Ghost instance or check if you have an ad blocker that is hiding the comments widget.

**Comment by fisenkodv** [comment]
@eddiesigner how about this:
if let's say `discusSiteName` variable is defined i.e. in the **Site Footer**, like 
```html
<script>const discusSiteName = "CHANGETHIS";</script>;
```
then the code block with a small modification mentioned [here](https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog) e.g.
```javascript
(function () {
  if(discusSiteName) {
    var d = document, s = d.createElement('script');
    s.src = `https://${discusSiteName}.disqus.com/embed.js`;
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  }
})();
```

will load Discuss comments.

**Comment by eddiesigner** [comment]
@fisenkodv Still you will need to edit the `post.hbs` file to uncomment the comment section, thus I think this way doesn't make a huge difference. I can't uncomment the comments section as default because not everyone wants comments in posts or not everyone uses Disqus.

**Comment by BurgerhoutJ** [comment]
I solved it. I had to uncomment the Disqus comment section. My mistake. Thanks guys!
