### ISSUE TITLE
Big speed regression with new version

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#256]
There was a big speed regression with new version of the theme. Mobile score is now 55 and the desktop version is 88. A quick look with Yellow Lab Tools shows fonts might be responsible for this.

<img width="938" alt="Screenshot 2020-08-07 at 8 10 26 PM" src="https://user-images.githubusercontent.com/1311831/89670547-138a5080-d8ea-11ea-9649-7498993c4b93.png">

**Comment by lapphan** [comment]
This theme supports multiple languages. So it must uses multiple languages font that causes the reported issue. It can not be considered as a bug. You must understand what you are trying to report. Please do some research. Yellow Lab doesn’t always right.

**Comment by eddiesigner** [comment]
This issue is misleading, your blog score is low due multiple problems originated by your customizations mostly, I've already explained to you multiple times that but it seems like you just don't care about those issues.

The font in the latest version supports multiple charsets (latin, vietnamese, greek and cyrillic) so it can be used in multiple languages, that's why you're seeing that "problem".

If you want to support only latin then you can use https://google-webfonts-helper.herokuapp.com/fonts to generate a custom font for your blog. After generating it you can follow the [steps described here](https://github.com/eddiesigner/liebling/issues/250#issuecomment-669503529) to know how to use it.

**Comment by lapphan** [comment]
I think [v.0.8.7](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.7) solved this issue.

**Comment by eddiesigner** [comment]
Yes, so now I'm closing this issue ;)
