### ISSUE TITLE
[Question] How do I create different categories?

### ISSUE THREAD

**Issue by ThePresence** [eddiesigner/liebling#261]
Hi,

How do I create different categories so that I can segregate all the posts based on categories instead of tags.

**Comment by eddiesigner** [comment]
Hi,

I think you're looking for content collections, [this a tutorial](https://ghost.org/tutorials/creating-content-collections/) on how to use them.

Since this is not a topic related to the theme itself, if you have further questions please head to the [forum](https://forum.ghost.org/) where you could find more help about this topic.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
