### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by Gabrunz** [eddiesigner/liebling#265]
How to add breadcrumbs in the post page ?

**Comment by eddiesigner** [comment]
I don't have plans to add breadcrumbs since Ghost doesn't have breadcrumbs support outside the box, if you really want to add breadcrumbs to your blog you might find these links useful:

* https://forum.ghost.org/t/idea-of-a-new-feature-breadcrumbs/14201
* https://notanengineer.com/coding/how-to-add-breadcrumbs-to-ghost/

At the end, is up to you to decide where exactly in the [post template](https://github.com/eddiesigner/liebling/blob/master/post.hbs) you wanna add them and how they would look like.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
