### ISSUE TITLE
Subscribe button loads continuously

### ISSUE THREAD

**Issue by galabuzik** [eddiesigner/liebling#267]
Newsletter button seems to load continuously and it doesn't add the members. I there something that I'am doing wrong?
![image](https://user-images.githubusercontent.com/19956502/92099598-6240e280-ede3-11ea-8842-176437913c83.png)

Try the website here: https://cloud-nodelab.com/

**Comment by eddiesigner** [comment]
It looks like there is a missconfiguration on your server, somehow your blog is using HTTPS but the request to the members API (which is managed by Ghost, not by the theme) is using HTTP, that's why the browser blocks it.

[This link](https://forum.ghost.org/t/ghost-subscriptions-insecure-content-blocked/10791) might helps you.

![CleanShot 2020-09-09 at 20 50 11](https://user-images.githubusercontent.com/1477503/92640815-1f4ca680-f2de-11ea-966a-2f34d6c988e2.png)

**Comment by galabuzik** [comment]
Thanks that worked, added the "https" to my config.development.json url
![Annotation 2020-09-09 232330](https://user-images.githubusercontent.com/19956502/92649580-edded580-f2f3-11ea-87ec-f15e69638477.png)
