### ISSUE TITLE
Make Liebling better compatible with Portal

### ISSUE THREAD

**Issue by timscha** [eddiesigner/liebling#294]
Hello @eddiesigner!

I'm trying to make the transition smoother to Ghosts Portal function. So I'd like to rewrite the "Subscribe" Button in the header to https://domain/#/portal/signup

I tried to achieve that with rewriting the redirects.json file as followed:

```
[{
    "from": "/newsletter/",
    "to": "/#/portal/signup/",
    "permanent": true
}]
```

Unfortunately that doesn`t work, the link still goes to /newsletter/

Do you have a idea to redirect it correctly?

Thank you
Tim

**Comment by timscha** [comment]
I figgured it out. 🤓 I had to remove the trailing Slash and also had to removed the membership parts in your routes.yaml.
But before I close this issue, maybe there is way to make it easier?

**Comment by eddiesigner** [comment]
Hi!

Unfortunately there isn't an ideal way to do it, you can do it by redirecting to `/signup` as you already did, you can also edit the `index.hbs` template and change the button url manually, you can even use Javascript to change the button url, but all of those options have pros and cons.

For now I removed the `routes.yaml` file since it's not even used by the theme, actually that file is ignored by Ghost if you don't upload it in the Ghost Admin.

I recommend you to download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.0) which fixes another issue with Portal.

**Comment by timscha** [comment]
Hi, Thank you for the further input. As my current solution works fine as I can see it, I will let everything as it is. :)
0.90 is already installed, Thanks! :)
