### ISSUE TITLE
cards' top border become square on home page

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#309]
hey I think I found the solution to this bug.
when you hover on the card, the images take the space.
you have to add overflow hidden on hover.
by the way I'm looking for a designer for my 2 websites ( a poker game and a music database).

**Comment by eddiesigner** [comment]
Hi, thanks for pointing that out, however the card image container already has `overflow: hidden`. I wasn't able to reproduce it but I found that adding `transform: translateZ(0)` to the container also fixes the issue. I added that property in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.2) so that should be fixed.

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
