### ISSUE TITLE
JS from polyfill.io is very slowly in some country, suggest include it from local js folder

### ISSUE THREAD

**Issue by chendelin1982** [eddiesigner/liebling#313]
liebling\default.hbs file have use the JS from polyfill.io, some time this JS access very slowly, need 30s
Suggest include it from local js folder

https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CPromise%2CArray.prototype.includes%2CString.prototype.endsWith%2CString.prototype.startsWith%2CObject.assign%2CNodeList.prototype.forEach

**Comment by eddiesigner** [comment]
In my tests that request just takes some milliseconds, of course it depends on your Internet connection but 30 seconds sounds pretty excessive since the response is pretty small. I won't create a local file with all those polyfills because then the content of that file will be loaded even if your browser supports those features. The good thing about Polyfill.io is that it only loads the polyfills if your browser doesn't support some of them, if it does then doesn't load anything.

If you don't want to give support to older browsers (IE 11 for instance) you can simply remove the following lines of code from the `default.hbs` template:

```html
<link rel="preconnect" href="https://polyfill.io">
<link rel="dns-prefetch" href="https://polyfill.io">

<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CPromise%2CArray.prototype.includes%2CString.prototype.endsWith%2CString.prototype.startsWith%2CObject.assign%2CNodeList.prototype.forEach"></script>
```

You can also create an issue in the [Polyfill.io repository](https://github.com/Financial-Times/polyfill-service/issues) to let them know that probably there is an issue with the script in some conditions like loading it from a specific country.

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
