### ISSUE TITLE
Support for multi tags on posts card

### ISSUE THREAD

**Issue by mehdihadeli** [eddiesigner/liebling#324]
Hi,
Could you support multiple tags on post card? 
![t](https://user-images.githubusercontent.com/3678399/106366372-a31c3380-6350-11eb-8cd2-202f56d9bdf2.jpg)

**Comment by eddiesigner** [comment]
Hi,

sorry but that's something that I won't implement because that would make the article cards so crowded, imagine having cards with over 5 or 10 tags or having cards with a couple of very long tags. A mechanism to solve these problems would not be so simple to implement. If you still want to implement that you can take a look to the Ghost themes documentation and give it a try ;)

**Comment by mehdihadeli** [comment]
Thanks, @eddiesigner, how can I customize your theme? Is it possible?

**Comment by eddiesigner** [comment]
You can fork it and make all your customisations there or you can simply do it in the theme folder that you already have, in both cases you have to modify the file `partials/loop.bhs` to add the tags in the article card. If you need to write or modify some CSS you can do it in the Ghost Admin (Code injection page). [This documentation](https://ghost.org/docs/themes/contexts/post/) might help you.

**Comment by mehdihadeli** [comment]
@eddiesigner Thanks for your guide :)
