### ISSUE TITLE
Code syntax highlighting with Prism. Wiki page update suggestion 

### ISSUE THREAD

**Issue by mausic** [eddiesigner/liebling#335]
Hi there!
Thanks for an amazing theme. I recently created my personal blog and decided to use your theme.

After my first publication went live, I received an email from Google that my blog-post has mobile usability issues:
- Contest wider than screen
- Clickable elements too close together

After some time spent digging the problem, I realized that issues were caused by `prism.js` syntax highlighting. I successfully solved the problem and would like to suggest to update the corresponding [wiki page](https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism) so others would have a solution as well.

To solve issues it is required to make the following update
```html
<style>
  code {
    overflow-x: auto;
  }
</style>
```

**Comment by Mausic** [comment]
Hi there!
Thanks for an amazing theme. I recently created my personal blog and decided to use your theme.

After my first publication went live, I received an email from Google that my blog-post has mobile usability issues:
- Contest wider than screen
- Clickable elements too close together

After some time spent digging the problem, I realized that issues were caused by `prism.js` syntax highlighting. I successfully solved the issue and would like to suggest to update corresponding [wiki page](https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism) so others would have a ready solution.

To solve issues it is required to make the following update
```html
<style>
  code {
    overflow-x: auto;
  }
</style>
```

**Comment by eddiesigner** [comment]
Hi!

Thanks for the heads up! I just released a [new version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.4) which kinda addresses this issue. In the new version I replaced `overflow: auto` with `overflow-x: auto` for the `pre` elements.

Your solution might solve that issue but it will render the scroll bar ~20px before the bottom of the container, that's why the overflow should happen in the `pre` element instead.

You also must know that the Google alerts are not always correct, sometimes you get that message if you have some sliders in place or something similar, that doesn't mean that your content is wider than the screen, it's simply a false-positive.

**Comment by Mausic** [comment]
Oh, thank you!

I'll check it out nearest future.

Yeah, I understand the situation with Google alerts, I just shared my solution on how I got rid from those annoying alerts in belief that it may help someone some time.

**Comment by eddiesigner** [comment]
I appreciate that!

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
