### ISSUE TITLE
/js/vendor/content-api.min.js.map/ - 404

### ISSUE THREAD

**Issue by danny88br** [eddiesigner/liebling#338]
Hi there,
/js/vendor/content-api.min.js.map/ returns 404 error, double checked on your demo site to be sure twice if it was me that was doing something wrong but it seems like that your demo site is affected too. Errors bug me :D

**Comment by eddiesigner** [comment]
Hi,

that file is irrelevant since it's just a mapping file that is not used by the theme, you can simply ignore it. If you prefer you're more than welcome to submit a PR to remove it from [content-api-min.js](https://github.com/eddiesigner/liebling/blob/master/src/js/vendor/content-api.min.js#L2) ;)

**Comment by eddiesigner** [comment]
I will close this issue now because the mapping file will be gone in the next update.
