### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by weeyin83** [eddiesigner/liebling#346]
It would be great if the theme could show the social media links at the top along with the main menu and supported more than Twitter and Facebook. 👍

**Comment by SurajSandhu** [comment]
Especially the Instagram option :)

**Comment by eddiesigner** [comment]
Ghost only supports Facebook and Twitter natively, that's why Liebling only supports those, if you want to add more social accounts you will need to add them manually in the code. [This has been discussed already](https://github.com/eddiesigner/liebling/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+social).

I don't really have plans to add social links in the top nav, at least not for now, I prefer having more space for the main menu. If you want to add them there you can do the following:

1. Unzip the theme folder and open the file `partials/header.hbs` with a text/code editor.

2. Add the following code _after_ [line 116](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L116)

```hbs
{{#if @site.facebook}}
  <a href="{{facebook_url @site.facebook}}" class="m-icon-button in-menu-main" target="_blank" rel="noopener" aria-label="Facebook">
    <span class="icon-facebook" aria-hidden="true"></span>
  </a>
{{/if}}
{{#if @site.twitter}}
  <a href="{{twitter_url @site.twitter}}" class="m-icon-button in-menu-main" target="_blank" rel="noopener" aria-label="Twitter">
    <span class="icon-twitter" aria-hidden="true"></span>
  </a>
{{/if}}
<a href="YOUR_INSTAGRAM_URL" class="m-icon-button in-menu-main" aria-label="Instagram">
  <span class="icon-instagram" aria-hidden="true"></span>
</a>
```

3. Save your changes, zip the theme folder and upload it again.

You can find the available icons in [this file](https://github.com/eddiesigner/liebling/blob/master/src/sass/common/_icons.scss) in case you need more social links.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
