### ISSUE TITLE
{{asset}} helper doesn't work for favicon

### ISSUE THREAD

**Issue by MrMebelMan** [eddiesigner/liebling#356]
### Issue Summary

Hello, I've tried to upload a transparent favicon via GUI, but Ghost adds a white background to it, so I've decided to insert a favicon link to default.hbs.

Unfortunately, {{asset}} helper path doesn't seem to work as it still displays the default ghost favicon.

I've ended up hard-coding the favicon path and ignoring the ghost warning about not using the {{asset}} helper.

### To Reproduce

1. Add favicon to /assets/favicon.ico
2. Add `<link rel="shortcut icon" type="image/x-icon" href="{{asset "favicon.ico"}}">` to default.hbs's header
3. Create a zip & upload the theme
4. Hard-refresh the website

**Comment by eddiesigner** [comment]
Hi,

I would suggest a couple of things:

1. Try to use a PNG file if possible
2. Try to move the file to `assets/images`
3. Make sure of adding your favicon after these lines:

```hbs
{{!-- This tag outputs SEO meta+structured data and other important settings --}}
{{ghost_head}}
```

Those lines output all meta tags including the favicon. If you want to overwrite the favicon then your code should be added after that in order to work, otherwise your change won't have effect.

**Comment by MrMebelMan** [comment]
@eddiesigner, I've already tried doing 2. and 3. without success :\
I'll try to use PNG. I doubt that it will help, but thanks anyway!

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
