### ISSUE TITLE
Featured post should not appear twice on main page

### ISSUE THREAD

**Issue by fredpchang** [eddiesigner/liebling#360]
I want to "feature" some articles on the home page, but featuring the most recent post results in duplicate entries. I hope the theme can be improved so that if article is in featured, it will not appear again next to it: 
<img width="1771" alt="Screen Shot 2021-04-17 at 6 21 58 PM" src="https://user-images.githubusercontent.com/43082100/115131066-d3678b80-9fa9-11eb-91d9-67d09ebcde1f.png">

**Comment by eddiesigner** [comment]
I'm not sure if this is really the desired behaviour, if you hide the featured articles because they appear in the slider there is a real chance that people won’t be able to see some of those posts, I think there is no issue if people see some post on different places, that's better than not seen some post at all.

If you really want to hide duplicate entries then you can do the following:

1. Unzip the theme folder.

2. Open the file `partials/loop.hbs` with a text/code editor.

3. Locate the following line:

````hbs
<article class="m-article-card {{#unless feature_image}}no-picture{{/unless}} {{post_class}}">
````

4. Replace it with this other line:

````hbs
<article class="m-article-card {{#unless feature_image}}no-picture{{/unless}} {{post_class}} {{#is "home"}}{{#if featured}}{{#has index="0, 1, 2, 3, 4"}}hide-card{{/has}}{{/if}}{{/is}}">
````

This line of code adds the class `hide-card` to the articles if they are featured, listed in the home page and if their index is less than 5 which is the max number of slides in the featured slider.

5. Save your changes.

6. Zip the theme folder and upload it again.

7. Inject the following style in the Ghost Admin (Settings -> Code injection -> Site Header):

````html
<style>
.hide-card {
  display: none !important;
}
</style>
````

8. Save your changes.

**Comment by fredpchang** [comment]
Thanks, Eduardo! That worked :)
