### ISSUE TITLE
Show locale in specific route

### ISSUE THREAD

**Issue by Arberoo** [eddiesigner/liebling#371]
Hello,

I am using /de/ and /it/ URLs to separate multi-language content, done with private #tags

This works fine as you can see here for example: https://blog.cakedefi.com/de/ and https://blog.cakedefi.com -- english content is shown in the main page, and german content in the /de/ page.

However, all the rest, like the Subscribe button etc. are still in english when visiting the /de/ page.

I translated everything in the locales de file but it's still not working. How can I make the whole page be displayed in german? I have the translations in the locales already.

**Comment by eddiesigner** [comment]
Hi,

In your case `/de` is just a tag, it's not really a language route. The theme uses the Publication Language from the Ghost Admin, that's why all the strings are in English. As you might notice, you can set only one language in the Ghost Admin.

I would suggest to take a look at this tutorial: https://ghost.org/docs/tutorials/multi-language-content/

Another option is using Weglot, you can find more info here: https://ghost.org/integrations/weglot/

**Comment by Arberoo** [comment]
Hey Eddie & thanks for all your help so far! Really appreciate it.

I have thoroughly gone through all documentation already but the language setup of our blog is still not optimal. When switching languages, the menu & featured blogpost still remains english (main language).

Would you be open to helping us properly setup our Blog language separation, as a paid job of course? You can reach out to me at arber@cakedefi.com 

Would be happy to hear from you :) 
Thanks

**Comment by eddiesigner** [comment]
Hi,

As I mentioned before, that happens because `/de` is just a tag route, the publication language is still English in the Ghost Admin. As you can see in the Admin, you can set only one language at a time, that's why I think Weglot is a good option since it handles everything for you and is easy to setup. If you don't want to use a service like that, you will need (as far as I know) to handle everything by yourself, you might even have to deal with the Ghost internals, that's something rather complex. The theme is not really responsible for handling that, you might wanna ask in [the forums](https://forum.ghost.org/) to see if someone from the Ghost staff can help you with that.

Another option is to have two different websites, each one on a separate subdomain, it might sound like a non-optimal solution but at the end it would work perfectly.

Btw, I'm afraid that currently I don't do that kind of work, sorry 😅

Cheers.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
