### ISSUE TITLE
Add TOC in post

### ISSUE THREAD

**Issue by magicgg91** [eddiesigner/liebling#372]
Hello,
I'm trying to add a Table of Content (TOC) in posts on my blog following the official guide provided by Ghost : https://ghost.org/docs/tutorials/adding-a-table-of-contents/#adding-a-table-of-contents-to-your-theme
It'w working perfectly with code injection or modifying theme if I add it inside content.
The best should be to have this TOC on the side of the post content, before the share/top buttons.
I've added them at this place, but I don't succeed to have a good presentation with colums in 100% of browser display, and I also don't know how to not display in mobile view.

Here is how it renders on my blog : 

Normal view, we don't see the entire TOC :
![l1](https://user-images.githubusercontent.com/16479933/118733824-5f850100-b83d-11eb-8305-a610e9b25407.PNG)

View with unzoom at 80%
![l2](https://user-images.githubusercontent.com/16479933/118733889-82afb080-b83d-11eb-98cd-41529e0af752.PNG)

Mobile view:
![l3](https://user-images.githubusercontent.com/16479933/118733990-b7236c80-b83d-11eb-957d-8c2dc6c34d24.PNG)

Do you think you can guide me on how to implement this on best way ? Or include this into your great theme and let user enable it with a parameter if he wants, like it's done for fade animation or search key (if possible).

Thanks in advance.

Guillaume

**Comment by eddiesigner** [comment]
Hi,

I'm afraid that I don't have plans to implement this feature. I can't also provide a full description on how to implement it in a good way since that will require deep changes in the current layout, sorry.

What I can tell you is that you will probably have to remove/reset all the styles for desktop on the classes `m-share`, `m-share__content` and `m-icon-button in-share` so the share bar is always fixed at the bottom, just like it happens on mobile, that way you will have enough space on the right side.

Then you can add the following styles:

```html
<style>
@media only screen and (min-width: 48rem) {
	.l-content .l-wrapper.in-post {
		display: flex;
		max-width: 1200px; /* Or any other width */
	}
}
</style>
```

Then add your TOC right after the div with the class `l-post-content`. The code might look like this:

```html
<div class="l-content in-post">
	<div class="l-content in-post">
        <div class="l-wrapper in-post js-aos-wrapper aos-init aos-animate">
			<div class="l-post-content js-progress-content">
				<!-- More code -->
			</div>
			<!-- Your TOC goes here -->
		</div>
</div>
```

Of course that's just a very rough implementation, you still have to adjust more styles and probably fix some issues, but at least I think it can gives you an idea of how it can be implemented properly.

**Comment by magicgg91** [comment]
Thanks for your answer, I will have a look at your suggestions and try to set it up.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
