### ISSUE TITLE
Logo in dark mode

### ISSUE THREAD

**Issue by chiragnd** [eddiesigner/liebling#383]
Hi, 

Since the theme pulls the logo from Ghost, how/where can we set up an alternative image for dark mode so that it transitions well? Thanks!

**Comment by eddiesigner** [comment]
Hi,

This was already discussed [here](https://github.com/eddiesigner/liebling/issues/297) and [here](https://github.com/eddiesigner/liebling/issues/204).

Another option could be hosting the second logo somewhere else and then open the file `partials/header.hbs` and adapt the following code:

```hbs
<a href="{{@site.url}}" class="m-logo in-mobile-topbar">
  <img src="{{@site.logo}}" alt="{{@site.title}}">
</a>
```

```hbs
<a href="{{@site.url}}" class="m-logo">
  <img src="{{@site.logo}}" alt="{{@site.title}}">
</a>
```

You will need to include your second logo in both places using the same code and changing the url, then you will need to inject some styles in the Ghost Admin to hide/show one of the two logos based on the theme mode.

I can't give you a full description because this is a deep customisation, but at least you have some options ;)

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
