### ISSUE TITLE
Avatars in the author page lack border

### ISSUE THREAD

**Issue by cmprmsd** [eddiesigner/liebling#384]
Currently the atuhor avatar does not have a black or white border in the /author/username page.
![image](https://user-images.githubusercontent.com/73472903/122212711-72c0d600-cea8-11eb-9952-cde66c382113.png)

For blog previews 
![image](https://user-images.githubusercontent.com/73472903/122212628-5ae95200-cea8-11eb-98c0-5334a5e87c14.png)

and on the settings page (/ghost/#/staff/username/)
![image](https://user-images.githubusercontent.com/73472903/122212642-6177c980-cea8-11eb-9a66-9da2891d4f0e.png)

it works just fine. I guess this can be fixed with a css tag for the element.

Great themes btw! Funny you use German names for them :)

**Comment by eddiesigner** [comment]
Hi,

Yeah, that's how it was intended 😅, back in the day I thought the border wasn't really necessary when the avatar is big, that's why that element doesn't have a border, I'm not sure if it really needs it but you can add it by injecting this code in the Ghost Admin:

```html
<style>
.m-hero-avatar {
	border: 2px solid #fff;
}
</style>
```

Haha yeah, I use German words because I'm learning that language 🙈

**Comment by cmprmsd** [comment]
Dankeschön für den Befehl und viel Glück! 😁👍

**Comment by eddiesigner** [comment]
Vielen Dank! 🤩
