### ISSUE TITLE
Newsletter does not work

### ISSUE THREAD

**Issue by Leovaldez42** [eddiesigner/liebling#409]
When I fill an email in the newsletter field and click the subscribe button, the user does not get added to it. I am not sure like do I have to follow some steps for that or was something wrong with my configuration. Can you help me with this?

**Comment by Leovaldez42** [comment]
Yes sure.
My website is [Thinkbrew](https://www.thinkbrew.in). I am using Mailgun to send emails and am able to send mails if I manually add the members in the dashboard, but when I try to add an email through the newsletter the email does not get added to the mailing list.

**Comment by eddiesigner** [comment]
It seems like you didn't check if your `url` value in your [Ghost config file](https://ghost.org/docs/config/) uses `https` as I suggested.

Currently your website has the following errors:

![CleanShot 2021-10-12 at 11 09 56](https://user-images.githubusercontent.com/1477503/136927256-7fadb3f0-c69b-42be-960c-f331d17c05e5.png)

Those errors are generated because the `url` value in your config file still uses `http`, therefore the subscription form doesn’t work.

Once you fix that issue it should work fine. If you don't know how to change the `url` value please ask in the [Ghost forum](https://forum.ghost.org/) since that is not related to the theme.

**Comment by AmreshSinha** [comment]
I am not able to send email too! My `config.production.json` is fine. I have set up mailgun through ghost dashboard.
My ghost version is 5.2.3. I was able to run this theme on ghost v5 with some tweaks.
It's currently throwing error 504 :/
Any help pls!

![image](https://user-images.githubusercontent.com/35039730/175918150-0beffe87-78cc-41d0-ad1e-9d2234d78997.png)
