### ISSUE TITLE
Only 6 pages are available. Page 7+/12 are not generated

### ISSUE THREAD

**Issue by abarajithan11** [eddiesigner/liebling#443]
I am unable to load any page after 6th, in index and in the tag pages. They are not generated.

Homepage: [Aba's Blog](https://aba-blog.xyz/index.html)
6th page: https://aba-blog.xyz/page/6/index.html
7th page (fails): https://aba-blog.xyz/page/7/index.html

![image](https://user-images.githubusercontent.com/26372005/151083768-858de4f9-5ee6-4f13-866e-382ee08b545a.png)
![image](https://user-images.githubusercontent.com/26372005/151083975-6bea361d-86c8-476d-ae9a-6864a87b0192.png)
![image](https://user-images.githubusercontent.com/26372005/151084047-e87a0b43-e56e-49d9-be0b-137924d23468.png)

**Comment by eddiesigner** [comment]
It seems that you're storing and loading your posts in a different way, I don't think this is an issue with the theme since Liebling is using the standard method to load the next and previous posts by using the [corresponding helpers](https://ghost.org/docs/themes/helpers/pagination/).

I'm afraid that I can't help you here, I would suggest you to debug your implementation or to look for help in [the forums](https://forum.ghost.org/).

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
