### ISSUE TITLE
Share icons missing on iOS Safari

### ISSUE THREAD

**Issue by dschwertfeger** [eddiesigner/liebling#450]
While trying out your demo theme, I noticed the share icons at the bottom are missing on iOS Safari. Only the reading-progress icon is shown. Doesn't seem to be an issue with Chrome on IOS, though. 

Do you have any idea why that might be happening and how to fix it?

**Comment by eddiesigner** [comment]
This usually happens if you have an ad blocker of some Safari extension that blocks social media buttons, please check if you have something like that enabled and try to disable it and test it again.

Please be aware that the theme can't prevent that behaviour and the only way to fix this is by disabling such apps/extensions.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to open another one if needed.
