### ISSUE TITLE
data-theme being set on page load, preventing prefers-color-scheme from changing theme

### ISSUE THREAD

**Issue by gradiian** [eddiesigner/liebling#454]
On initial page load, the `html` tag has `data-theme="dark"` set which prevents `prefers-color-scheme` from being able to change themes automatically. If I manually set it to an empty value: `<html data-theme="">`, the theme changes based on the system's theme until it's been overridden by the manual toggle.

**Comment by eddiesigner** [comment]
This is actually the desired behaviour, as soon as you set the theme by pressing the dark mode toggle a setting is saved in local storage in order to persist your preference, thus `prefers-color-scheme` is ignored.

When the page loads the theme checks if a mode preference is stored locally, if it finds it then applies the correct mode based on that value. If there is no preference stored then the mode changes automatically according to the `prefers-color-scheme` system preference.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to open another one if needed.
