### ISSUE TITLE
Customize css sass in liebling?

### ISSUE THREAD

**Issue by stemativablog** [eddiesigner/liebling#461]
I help. How do I customize css sass in liebling?

**Comment by eddiesigner** [comment]
If you want to make small changes it's better that you inject your styles in the Ghost Admin in order to persist your changes if later you install a new version of the theme, otherwise your changes will be overwritten, you can do that in Settings --> Code injection --> Site Header

If you want to implement deeper changes you can follow [this guide](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) to setup a development environment  where you can modify the source files, for example the SASS files.
