### ISSUE TITLE
Typeface Request

### ISSUE THREAD

**Issue by adebayo-moses** [eddiesigner/liebling#473]
Hi Eddie, Liebling is a great theme, one of the best CMS themes, but can you allow choosing different typefaces or try out a different font from development, the source sans pro typeface looks somehow, won't say boring but it's not allowing the theme reach full potentials.

Might consider Inter, Lato or some other nice fonts.

**Comment by eddiesigner** [comment]
Hi Moses,

Thanks for your input, I appreciate it. However, I'm afraid that providing different typefaces is something that I don't plan to do it, the reason is because it's a bit tricky to implement, I don't want to increase the size of the zip file by including multiple font files that users might or might not use. Using Google fonts directly is not an option due GDPR concerns.

What I could do in the future is to change the current typeface, Inter and Lato are good options, I will think about it 👍🏻

In the meantime, if you want to change the font you can follow the steps described in [this thread](https://github.com/eddiesigner/liebling/issues/250).

**Comment by adebayo-moses** [comment]
Yeah, I actually thought of going through that process already, even before i saw the thread, just had to inform you as some people are not really tech savvy and may also want to change the typeface. I'll change the fonts myself, Thank you Eddie.
