### ISSUE TITLE
Liebling customization

### ISSUE THREAD

**Issue by beatljuice** [eddiesigner/liebling#478]
I am interested in your Ghost.org theme, Liebling, and have a couple of questions before making a final decision.

1. I want my website homepage header to have a prominent interactive "SEARCH" element, similar to the one found in this website: https://www.bestreviews.guide/   
(I tried to attach a screenshot here)

2. I was unable to find a "Style Guide" for your theme that shows what quoted text or in-line bulleted lists or Toggle content looks like - is that available?

![image](https://user-images.githubusercontent.com/8432851/188499250-2df4dd76-0e17-43ad-9080-e58af9a6dbff.png)

**Comment by eddiesigner** [comment]
I'm afraid that if you want to have a similar search element you have to develop it by yourself since I don't provide custom work like this.

Yeah, unfortunately at the moment there is no style guide available, the theme supports all the content blocks available in the Ghost editor but you can't see them in the current live demo, sorry.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
