### ISSUE TITLE
Product description doesn’t allow link on picture

### ISSUE THREAD

**Issue by charlies2022** [eddiesigner/liebling#481]
Hi. When I use the Product Recommendation it allows to add a link on any text, a button, but it doesn’t allow to add a link to the picture. Is there any way I can do this? Thanks in advance.

**Comment by eddiesigner** [comment]
Hi, as far as I know there is no way to add a link to the picture at the moment.

As a workaround you could create a Product card and then inspect your page and copy the generated HTML. You can paste that code in a HTML card and add a link sorounding the image manually.

I would also suggest to contact the [Ghost support](mailto:support@ghost.org) since this is not really related to the theme.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
