### ISSUE TITLE
Blockquote style between editor and preview/published view

### ISSUE THREAD

**Issue by bastienperez** [eddiesigner/liebling#490]
Hello,

The `blockquote` style is not the same in Editor and Preview/Publish view.

In editor, it looks like this (the style I want):
<img width="264" alt="blockquote-editor" src="https://user-images.githubusercontent.com/104252785/201515950-81f9fbe9-808d-4cdf-874c-99be4404771d.png">

In preview/published, it looks like this:
<img width="298" alt="blockquote-published" src="https://user-images.githubusercontent.com/104252785/201515953-0576879a-e603-436e-ac52-f36176e44b54.png">

I guess it's due to CSS in Koenig. A similar issue is referenced in the Ghost GitHub https://github.com/TryGhost/Ghost/issues/10666

**Comment by eddiesigner** [comment]
Hi,

This is because the theme includes custom styles for blockquotes which don't necessary have the same appearance as the ones from the Ghost editor, if you want to have the same style you can override the custom ones by injecting the following code in the Ghost Admin (Settings --> Code injection --> Site Header):

```html
<style>
.l-post-content blockquote::before {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    width: 0.3rem;
    background: var(--ghost-accent-color);
}
</style>
```

**Comment by bastienperez** [comment]
Thanks a lot it works!
