### ISSUE TITLE
Getting Error: Usage of {{@labs.members}} is no longer supported

### ISSUE THREAD

**Issue by severus-tux** [eddiesigner/liebling#507]
I recently upgraded to Ghost V5. SInce then, I am getting this error while trying to install liebling. 

![image](https://user-images.githubusercontent.com/21301040/216909759-ecc3fcca-4903-4802-a5c1-929696e8527f.png)
![image](https://user-images.githubusercontent.com/21301040/216909897-6338dd7f-3b55-41de-b70b-b5b661c13515.png)

**Comment by eddiesigner** [comment]
I'm wondering what version of the theme you have installed? The theme replaced those helpers since version 2.0.0 (June, 2022), if you [search in the latest version](https://github.com/eddiesigner/liebling/search?q=site.members_enabled) you can see the new helpers.

I would suggest you to download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v2.1.2) from the releases page.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
