### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by stephenajulu** [eddiesigner/liebling#54]
Kindly create a dark version. I would realy appreciate. I am interested in paying 20 dollars for this.

**Comment by eddiesigner** [comment]
I think I'll implement a dark version since more users are requesting this feature, although I will have to change many things because the theme is not ready at the moment to support a dark version.

It won't be a different theme though, it would be the same but with the dark appeareance enabled if your operating system has it enabled as well (that detection will happen automatically).

I'll write you over here when the dark version is ready.

**Comment by stephenajulu** [comment]
Thank you very much. I am willing to help you any way i can. Though i am just a newby to Web Development, Ghost and static site. Tried to do it on my own but failed. 

Thank you again. i appreciate it.

**Comment by eddiesigner** [comment]
@stephenajulu Just to let you know the latest release already supports dark mode 🌓👌🏼

**Comment by stephenajulu** [comment]
Thank you very very much. Kudos! Let me set it up. 
Thanks again!
