### ISSUE TITLE
Google Lighthouse Score Improvement

### ISSUE THREAD

**Issue by ajeet001** [eddiesigner/liebling#66]
Not a complain but an **improvement** would be good when it comes to Google lighthouse score.
Especially the SEO and Best practices part.

![image](https://user-images.githubusercontent.com/30115193/66693103-e0276700-ecc2-11e9-9cc7-35126c96ee8e.png)

Here is the report

[lighthouse.pdf](https://github.com/eddiesigner/liebling/files/3720064/lighthouse.pdf)

**Comment by eddiesigner** [comment]
I saw the report and also generated my own report and it seems like the main issues are related to the images. I can't do much about it since the theme itself is not responsible of how the images are managed. For instance, the issue `Serve images in next-gen formats` is related to Ghost itself or even with you because you can choose the format you want and then upload those images to the platform.

The issue `Avoid enormous network payloads` is also related to images sizes, to improve that you can upload smaller or compressed images. Maybe I can implement lazy load to load them just when needed.

The issue `Does not use passive listeners to improve scrolling performance` is related to some third party plugin I use. I guess I can report it as an issue and wait until they solve it.

**Comment by eddiesigner** [comment]
The newest version (v.0.5.5) implements lazy load for images and fixes the issue with the `font-display` property 😃
